#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const agentDir = process.argv[2] || path.join(process.env.USERPROFILE || process.env.HOME, ".pi", "agent");
const root = path.join(agentDir, "npm", "node_modules", "@tintinweb", "pi-subagents");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
if (pkg.version !== "0.14.3") throw new Error(`Refusing pi-subagents ${pkg.version}; patch is pinned to 0.14.3`);
const replace = (rel, oldText, newText) => {
  const file = path.join(root, "src", rel);
  let text = fs.readFileSync(file, "utf8");
  if (text.includes(newText)) return;
  if (!text.includes(oldText)) throw new Error(`Upstream drift in ${rel}: ${oldText.slice(0, 80)}`);
  text = text.replace(oldText, newText);
  fs.writeFileSync(file, text, "utf8");
};

replace("types.ts", "export interface AgentRecord {\n  id: string;", `export interface AgentRecord {\n  id: string;\n  /** MY_SMART_PI_NESTED_FLEET: ancestry and compact live telemetry. */\n  parentId?: string;\n  depth: number;\n  currentTool?: string;\n  turnCount: number;\n  modelId?: string;`);

replace("agent-manager.ts", "interface SpawnOptions {\n  description: string;", `interface SpawnOptions {\n  description: string;\n  parentId?: string;\n  depth?: number;\n  /** Activation-scoped completion handler for nested child sessions. */\n  onComplete?: OnAgentComplete;`);
replace("agent-manager.ts", "      id,\n      type,\n      description: options.description,", `      id,\n      type,\n      parentId: options.parentId,\n      depth: options.depth ?? 1,\n      currentTool: undefined,\n      turnCount: 0,\n      modelId: options.model ? \`${'${options.model.provider}/${options.model.id}'}\` : undefined,\n      description: options.description,`);
replace("agent-manager.ts", `      onToolActivity: (activity) => {\n        if (activity.type === "end") record.toolUses++;\n        options.onToolActivity?.(activity);\n      },\n      onTurnEnd: options.onTurnEnd,`, `      onToolActivity: (activity) => {\n        record.currentTool = activity.type === "start" ? activity.toolName : undefined;\n        if (activity.type === "end") record.toolUses++;\n        options.onToolActivity?.(activity);\n      },\n      onTurnEnd: (turnCount) => { record.turnCount = turnCount; options.onTurnEnd?.(turnCount); },`);
replace("agent-manager.ts", "      agentId: id,\n      model: options.model,", "      agentId: id,\n      parentDepth: record.depth,\n      model: options.model,");
replace("agent-manager.ts", "          try { this.onComplete?.(record); } catch { /* ignore completion side-effect errors */ }\n        } else {\n          this.runningBackground--;\n          try { this.onComplete?.(record); } catch { /* ignore completion side-effect errors */ }", "          try { (options.onComplete ?? this.onComplete)?.(record); } catch { /* ignore completion side-effect errors */ }\n        } else {\n          this.runningBackground--;\n          try { (options.onComplete ?? this.onComplete)?.(record); } catch { /* ignore completion side-effect errors */ }");
replace("agent-manager.ts", "          this.onComplete?.(record);\n        } else {\n          this.runningBackground--;\n          this.onComplete?.(record);", "          (options.onComplete ?? this.onComplete)?.(record);\n        } else {\n          this.runningBackground--;\n          (options.onComplete ?? this.onComplete)?.(record);");
replace("agent-manager.ts", "        record.completedAt = Date.now();\n        this.onComplete?.(record);", "        record.completedAt = Date.now();\n        (next.args.options.onComplete ?? this.onComplete)?.(record);");

replace("agent-runner.ts", `import { readFileSync } from "node:fs";`, `import { readFileSync } from "node:fs";\nimport { AsyncLocalStorage } from "node:async_hooks";`);
replace("agent-runner.ts", `import type { SubagentType, ThinkingLevel } from "./types.js";`, `import type { SubagentType, ThinkingLevel } from "./types.js";\n\nexport type NestedAgentContext = { parentId?: string; depth: number };\nconst NESTED_CONTEXT_KEY = Symbol.for("pi-subagents:nested-context");\nconst nestedContextStorage: AsyncLocalStorage<NestedAgentContext> =\n  ((globalThis as any)[NESTED_CONTEXT_KEY] ??= new AsyncLocalStorage<NestedAgentContext>());\nexport const getNestedAgentContext = (): NestedAgentContext => nestedContextStorage.getStore() ?? { depth: 0 };`);
replace("agent-runner.ts", "  await loader.reload();", `  await nestedContextStorage.run(\n    { parentId: options.agentId, depth: options.parentDepth ?? 1 },\n    () => loader.reload(),\n  );`);
replace("agent-runner.ts", "  agentId?: string;\n", "  agentId?: string;\n  parentDepth?: number;\n");

replace("settings.ts", "export interface SubagentsSettings {\n  maxConcurrent?: number;", `export interface SubagentsSettings {\n  maxConcurrent?: number;\n  /** Maximum Agent -> Helper nesting depth. */\n  maxSubagentDepth?: number;`);
replace("settings.ts", "  if (\n    Number.isInteger(r.defaultMaxTurns)", `  if (Number.isInteger(r.maxSubagentDepth) && (r.maxSubagentDepth as number) >= 1 && (r.maxSubagentDepth as number) <= 8) {\n    out.maxSubagentDepth = r.maxSubagentDepth as number;\n  }\n  if (\n    Number.isInteger(r.defaultMaxTurns)`);
replace("settings.ts", "  setMaxConcurrent: (n: number) => void;", "  setMaxConcurrent: (n: number) => void;\n  setMaxSubagentDepth: (n: number) => void;");
replace("settings.ts", "  if (typeof s.maxConcurrent === \"number\") appliers.setMaxConcurrent(s.maxConcurrent);", "  if (typeof s.maxConcurrent === \"number\") appliers.setMaxConcurrent(s.maxConcurrent);\n  if (typeof s.maxSubagentDepth === \"number\") appliers.setMaxSubagentDepth(s.maxSubagentDepth);");

replace("index.ts", "getAgentConversation, getDefaultMaxTurns", "getAgentConversation, getDefaultMaxTurns, getNestedAgentContext");
replace("index.ts", "  const agentActivity = new Map<string, AgentActivity>();", `  // MY_SMART_PI_NESTED_FLEET\n  const activationContext = getNestedAgentContext();\n  const agentActivity = new Map<string, AgentActivity>();`);
replace("index.ts", "  const manager = new AgentManager((record) => {", `  const SHARED_MANAGER_KEY = Symbol.for("pi-subagents:shared-manager:0.14.3");\n  const existingManager = (globalThis as any)[SHARED_MANAGER_KEY] as AgentManager | undefined;\n  const ownsSharedManager = !existingManager;\n  const handleAgentComplete = (record: AgentRecord) => {`);
replace("index.ts", "    widget.update();\n  }, undefined, (record) => {", `    widget.update();\n  };\n  const manager = existingManager ?? new AgentManager(handleAgentComplete, undefined, (record) => {`);
replace("index.ts", "  });\n\n  // Expose manager via Symbol.for() global registry", `  });\n  if (ownsSharedManager) (globalThis as any)[SHARED_MANAGER_KEY] = manager;\n\n  // Expose manager via Symbol.for() global registry`);
replace("index.ts", "    manager.abortAll();\n    for (const timer", `    if (ownsSharedManager) {\n      manager.abortAll();\n      manager.dispose();\n      if ((globalThis as any)[SHARED_MANAGER_KEY] === manager) delete (globalThis as any)[SHARED_MANAGER_KEY];\n    }\n    for (const timer`);
replace("index.ts", "    fleet.dispose();\n    manager.dispose();", "    fleet.dispose();");
replace("index.ts", "  let toolDescriptionMode: ToolDescriptionMode = \"full\";", `  let maxSubagentDepth = 2;\n  function setMaxSubagentDepth(n: number): void { maxSubagentDepth = Math.max(1, n); }\n  let toolDescriptionMode: ToolDescriptionMode = "full";`);
replace("index.ts", "      setMaxConcurrent: (n) => manager.setMaxConcurrent(n),", "      setMaxConcurrent: (n) => manager.setMaxConcurrent(n),\n      setMaxSubagentDepth,");
replace("index.ts", "      maxConcurrent: manager.getMaxConcurrent(),", "      maxConcurrent: manager.getMaxConcurrent(),\n      maxSubagentDepth,");
replace("index.ts", "      // Resume existing agent\n      if (params.resume)", `      if (!params.resume && activationContext.depth >= maxSubagentDepth) {\n        return textResult(\`Maximum subagent depth ${'${maxSubagentDepth}'} reached; this agent is a non-delegating leaf.\`);\n      }\n\n      // Resume existing agent\n      if (params.resume)`);
replace("index.ts", "            description: params.description,\n            model,", "            description: params.description,\n            parentId: activationContext.parentId,\n            depth: activationContext.depth + 1,\n            onComplete: handleAgentComplete,\n            model,");
replace("index.ts", "          description: params.description,\n          model,", "          description: params.description,\n          parentId: activationContext.parentId,\n          depth: activationContext.depth + 1,\n          onComplete: handleAgentComplete,\n          model,");
replace("index.ts", `  pi.registerCommand("agents", {`, `  pi.registerCommand("fleet", {\n    description: "Focus the hierarchical live Agent fleet",\n    handler: async (_args, ctx) => {\n      fleet.setUICtx(ctx.ui as unknown as FleetUICtx);\n      fleet.focusNext(false);\n    },\n  });\n\n  pi.registerCommand("agents", {`);

replace("ui/fleet-list.ts", "  // ---- Lifecycle ----", `  /** Direct command/keybinding entry point. */\n  focusNext(reverse = false): void {\n    const max = this.roster().length - 1;\n    if (max < 1) { this.ui?.notify("No live agents.", "info"); return; }\n    this.active = true;\n    this.selectedIndex = reverse\n      ? (this.selectedIndex <= 0 ? max : this.selectedIndex - 1)\n      : (this.selectedIndex >= max ? 0 : this.selectedIndex + 1);\n    this.update();\n  }\n\n  // ---- Lifecycle ----`);
replace("ui/fleet-list.ts", "    if (!this.active) {\n      // Activate", `    if (matchesKey(data, "tab") || matchesKey(data, "shift+tab")) {\n      if (this.agentRecords().length > 0 && this.ui.getEditorText() === "") {\n        this.focusNext(matchesKey(data, "shift+tab"));\n        return { consume: true };\n      }\n    }\n\n    if (!this.active) {\n      // Activate`);
replace("ui/fleet-list.ts", `    return this.manager.listAgents()\n      .filter(a => a.session && (\n        a.status === "running" || a.status === "queued"\n        || a.id === this.viewingAgentId\n        || (a.completedAt != null && now - a.completedAt < FINISHED_LINGER_MS)\n      ))\n      .sort((a, b) => a.startedAt - b.startedAt);`, `    const records = this.manager.listAgents().filter(a => a.session && (\n      a.status === "running" || a.status === "queued"\n      || a.id === this.viewingAgentId\n      || (a.completedAt != null && now - a.completedAt < FINISHED_LINGER_MS)\n    ));\n    const byParent = new Map<string | undefined, AgentRecord[]>();\n    for (const record of records) {\n      const key = records.some(r => r.id === record.parentId) ? record.parentId : undefined;\n      const siblings = byParent.get(key) ?? [];\n      siblings.push(record);\n      byParent.set(key, siblings);\n    }\n    for (const siblings of byParent.values()) siblings.sort((a, b) => a.startedAt - b.startedAt);\n    const ordered: AgentRecord[] = [];\n    const append = (parentId?: string) => {\n      for (const record of byParent.get(parentId) ?? []) { ordered.push(record); append(record.id); }\n    };\n    append();\n    return ordered;`);
replace("ui/fleet-list.ts", `    const left = \`  ${'${this.bullet(rosterIndex, sel, theme)}'} ${'${theme.fg("muted", getDisplayName(record.type))}'}  ${'${record.description}'}\`;`, `    const branch = record.depth > 1 ? "  ".repeat(record.depth - 1) + "└─ " : "";\n    const live = [record.status, record.modelId, record.currentTool ? "tool:" + record.currentTool : undefined, "t" + record.turnCount].filter(Boolean).join(" · ");\n    const left = "  " + this.bullet(rosterIndex, sel, theme) + " " + branch + theme.fg("muted", getDisplayName(record.type)) + "  " + record.description + "  " + theme.fg("dim", live);`);

console.log("Patched @tintinweb/pi-subagents 0.14.3: strict shared nested Fleet runtime.");
